config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-api-spec:
      branch: master
      repo: https://github.com/EOSC-synergy/sqaaas-api-spec
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: feature/gosec
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/EOSC-synergy/sqaaas-api-spec git:
        commands:
        - /usr/bin/env sh .sqa/script.snazzy-rose-skunk.sh
        container: qc.acc_squeaky-lavender-uguisu
  QC.Doc:
    repos:
      github.com/EOSC-synergy/sqaaas-api-spec find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.greasy-auburn-scorpion.sh
        container: qc.doc_bluesy-amber-uguisu
      github.com/EOSC-synergy/sqaaas-api-spec git:
        commands:
        - /usr/bin/env sh .sqa/script.queasy-platinum-bongo.sh
        container: qc.doc_snappy-wisteria-cuttlefish
      github.com/EOSC-synergy/sqaaas-api-spec markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.muzzy-tomato-cuttlefish.sh
        container: qc.doc_hazy-heliotrope-coral
  QC.Lic:
    repos:
      github.com/EOSC-synergy/sqaaas-api-spec licensee:
        commands:
        - /usr/bin/env sh .sqa/script.hilly-chestnut-dragon.sh
        container: qc.lic_nippy-denim-gibbon
  QC.Sec:
    repos:
      github.com/EOSC-synergy/sqaaas-api-spec gosec:
        commands:
        - /usr/bin/env sh .sqa/script.smelly-maroon-civet.sh
        container: qc.sec_trippy-malachite-ragdoll
  QC.Ver:
    repos:
      github.com/EOSC-synergy/sqaaas-api-spec get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.snappy-cinnabar-nightingale.sh
        container: qc.ver_jumpy-auburn-ragdoll
timeout: 1800
