config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-api-spec:
      branch: master
      repo: https://github.com/EOSC-synergy/sqaaas-api-spec
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: release/1.7.0
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/EOSC-synergy/sqaaas-api-spec git:
        commands:
        - /usr/bin/env sh .sqa/script.gimpy-champagne-macaw.sh
        container: qc.acc_bumpy-brown-collie
  QC.Doc:
    repos:
      github.com/EOSC-synergy/sqaaas-api-spec find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.flabby-smalt-greyhound.sh
        container: qc.doc_homely-plum-alligator
      github.com/EOSC-synergy/sqaaas-api-spec git:
        commands:
        - /usr/bin/env sh .sqa/script.hazy-charcoal-chinook.sh
        container: qc.doc_stealthy-khaki-reindeer
      github.com/EOSC-synergy/sqaaas-api-spec markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.ugly-eggplant-akita.sh
        container: qc.doc_chummy-alizarin-robin
  QC.Lic:
    repos:
      github.com/EOSC-synergy/sqaaas-api-spec licensee:
        commands:
        - /usr/bin/env sh .sqa/script.woozy-buff-goat.sh
        container: qc.lic_surly-cardinal-wasp
  QC.Ver:
    repos:
      github.com/EOSC-synergy/sqaaas-api-spec get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.stuffy-cardinal-heron.sh
        container: qc.ver_seedy-burgundy-cattle
timeout: 1800
