config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-api-spec:
      branch: master
      repo: https://github.com/EOSC-synergy/sqaaas-api-spec
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: 1.6.0-alpha5
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/EOSC-synergy/sqaaas-api-spec git:
        commands:
        - /usr/bin/env sh .sqa/script.surly-salmon-hamster.sh
        container: qc.acc_sunny-pumpkin-opossum
  QC.Doc:
    repos:
      github.com/EOSC-synergy/sqaaas-api-spec find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.pretty-apricot-chicken.sh
        container: qc.doc_jumpy-ultramarine-cassowary
      github.com/EOSC-synergy/sqaaas-api-spec markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.snappy-heliotrope-gar.sh
        container: qc.doc_frumpy-rose-wasp
  QC.Lic:
    repos:
      github.com/EOSC-synergy/sqaaas-api-spec licensee:
        commands:
        - /usr/bin/env sh .sqa/script.flabby-thistle-cat.sh
        container: qc.lic_squirrely-brown-bonobo
  QC.Ver:
    repos:
      github.com/EOSC-synergy/sqaaas-api-spec is_semver.py:
        commands:
        - /usr/bin/env sh .sqa/script.wiggy-carmine-ladybird.sh
        container: qc.ver_scanty-green-tarsier
timeout: 600
