config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: release/1.7.0
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/eosc-synergy/sqaaas-api-spec:
      branch: master
      repo: https://github.com/eosc-synergy/sqaaas-api-spec
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/eosc-synergy/sqaaas-api-spec git:
        commands:
        - /usr/bin/env sh .sqa/script.gamy-magenta-tortoise.sh
        container: qc.acc_messy-mauve-bear
  QC.Doc:
    repos:
      github.com/eosc-synergy/sqaaas-api-spec find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.gamy-myrtle-donkey.sh
        container: qc.doc_hilly-coral-bombay
      github.com/eosc-synergy/sqaaas-api-spec git:
        commands:
        - /usr/bin/env sh .sqa/script.trippy-bistre-turkey.sh
        container: qc.doc_pokey-fuchsia-akbash
      github.com/eosc-synergy/sqaaas-api-spec markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.crappy-lavender-okapi.sh
        container: qc.doc_grumpy-coral-frigatebird
  QC.FAIR:
    repos:
      github.com/eosc-synergy/sqaaas-api-spec F-UJI:
        commands:
        - /usr/bin/env sh .sqa/script.wiggy-smalt-chicken.sh
        container: qc.fair_lovely-crimson-anteater
  QC.Lic:
    repos:
      github.com/eosc-synergy/sqaaas-api-spec licensee:
        commands:
        - /usr/bin/env sh .sqa/script.woolly-silver-barb.sh
        container: qc.lic_dorky-amethyst-dhole
  QC.Ver:
    repos:
      github.com/eosc-synergy/sqaaas-api-spec get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.slaphappy-ivory-mayfly.sh
        container: qc.ver_freaky-khaki-rhinoceros
timeout: 1800
