config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-api-spec:
      branch: master
      repo: https://github.com/EOSC-synergy/sqaaas-api-spec
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: release/1.7.0
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/EOSC-synergy/sqaaas-api-spec git:
        commands:
        - /usr/bin/env sh .sqa/script.trippy-myrtle-fish.sh
        container: qc.acc_lovely-orange-bordeaux
  QC.Doc:
    repos:
      github.com/EOSC-synergy/sqaaas-api-spec find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.crabby-goldenrod-pig.sh
        container: qc.doc_beady-silver-catfish
      github.com/EOSC-synergy/sqaaas-api-spec git:
        commands:
        - /usr/bin/env sh .sqa/script.woolly-turquoise-abyssinian.sh
        container: qc.doc_nerdy-amethyst-beetle
      github.com/EOSC-synergy/sqaaas-api-spec markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.zippy-teal-mongrel.sh
        container: qc.doc_freaky-russet-lemming
  QC.Lic:
    repos:
      github.com/EOSC-synergy/sqaaas-api-spec licensee:
        commands:
        - /usr/bin/env sh .sqa/script.stuffy-scarlet-bat.sh
        container: qc.lic_sloppy-cerise-anteater
  QC.Ver:
    repos:
      github.com/EOSC-synergy/sqaaas-api-spec get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.geeky-cream-boar.sh
        container: qc.ver_smelly-sepia-schnauzer
timeout: 1800
