config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-api-spec:
      branch: master
      repo: https://github.com/EOSC-synergy/sqaaas-api-spec
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: release/1.7.0
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/EOSC-synergy/sqaaas-api-spec git:
        commands:
        - /usr/bin/env sh .sqa/script.snippy-magnolia-quoll.sh
        container: qc.acc_muggy-puce-tiger
  QC.Doc:
    repos:
      github.com/EOSC-synergy/sqaaas-api-spec find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.freaky-malachite-deer.sh
        container: qc.doc_scanty-chartreuse-tang
      github.com/EOSC-synergy/sqaaas-api-spec git:
        commands:
        - /usr/bin/env sh .sqa/script.boozy-eggplant-penguin.sh
        container: qc.doc_freaky-pumpkin-hound
      github.com/EOSC-synergy/sqaaas-api-spec markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.stinky-celadon-baboon.sh
        container: qc.doc_grumpy-firebrick-oriole
  QC.FAIR:
    repos:
      github.com/EOSC-synergy/sqaaas-api-spec F-UJI:
        commands:
        - /usr/bin/env sh .sqa/script.muggy-tan-wolverine.sh
        container: qc.fair_slimy-asparagus-hyena
  QC.Lic:
    repos:
      github.com/EOSC-synergy/sqaaas-api-spec licensee:
        commands:
        - /usr/bin/env sh .sqa/script.cozy-blue-woodpecker.sh
        container: qc.lic_bumpy-orchid-buzzard
  QC.Ver:
    repos:
      github.com/EOSC-synergy/sqaaas-api-spec get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.hilly-grey-seal.sh
        container: qc.ver_gamy-persimmon-swan
timeout: 1800
