config:
  credentials:
  - id: upv_im_id
    password_var: IM_PASS
    username_var: IM_USER
  - id: incd_openstack_id
    password_var: OPENSTACK_PASS
    username_var: OPENSTACK_USER
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: release/1.7.0
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/eosc-synergy/sqaaas-api-spec:
      branch: master
      repo: https://github.com/eosc-synergy/sqaaas-api-spec
    github.com/orviz/IM-sqaaas-test:
      branch: master
      repo: https://github.com/orviz/IM-sqaaas-test
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/eosc-synergy/sqaaas-api-spec git:
        commands:
        - /usr/bin/env sh .sqa/script.sloppy-teal-wallaby.sh
        container: qc.acc_homey-brass-rabbit
  QC.Doc:
    repos:
      github.com/eosc-synergy/sqaaas-api-spec find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.lanky-pear-whippet.sh
        container: qc.doc_lanky-sapphire-slug
      github.com/eosc-synergy/sqaaas-api-spec git:
        commands:
        - /usr/bin/env sh .sqa/script.gamy-burgundy-mongoose.sh
        container: qc.doc_breezy-alizarin-fowl
      github.com/eosc-synergy/sqaaas-api-spec markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.cranky-indigo-forest.sh
        container: qc.doc_sickly-mustard-leopard
  QC.FAIR:
    repos:
      github.com/eosc-synergy/sqaaas-api-spec F-UJI:
        commands:
        - /usr/bin/env sh .sqa/script.woozy-jade-raccoon.sh
        container: qc.fair_pasty-flax-mongrel
  QC.Lic:
    repos:
      github.com/eosc-synergy/sqaaas-api-spec licensee:
        commands:
        - /usr/bin/env sh .sqa/script.flabby-indigo-squirrel.sh
        container: qc.lic_snappy-celadon-pinscher
  QC.Ver:
    repos:
      github.com/eosc-synergy/sqaaas-api-spec get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.sloppy-mauve-fly.sh
        container: qc.ver_goopy-violet-frise
  SvcQC.Dep:
    repos:
      github.com/orviz/IM-sqaaas-test im_client:
        commands:
        - /usr/bin/env sh .sqa/script.fuzzy-firebrick-wolf.sh
        container: svcqc.dep_lumpy-cinnamon-ocelot
timeout: 1800
