config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-api-spec:
      branch: master
      repo: https://github.com/EOSC-synergy/sqaaas-api-spec
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: feature/gosec
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/EOSC-synergy/sqaaas-api-spec git:
        commands:
        - /usr/bin/env sh .sqa/script.scanty-maroon-swan.sh
        container: qc.acc_wheezy-lemon-akita
  QC.Doc:
    repos:
      github.com/EOSC-synergy/sqaaas-api-spec find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.homely-buff-cheetah.sh
        container: qc.doc_wheezy-pear-stingray
      github.com/EOSC-synergy/sqaaas-api-spec git:
        commands:
        - /usr/bin/env sh .sqa/script.beady-linen-wildebeest.sh
        container: qc.doc_skinny-wisteria-retriever
      github.com/EOSC-synergy/sqaaas-api-spec markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.snappy-xanthic-chameleon.sh
        container: qc.doc_snappy-malachite-ibis
  QC.Lic:
    repos:
      github.com/EOSC-synergy/sqaaas-api-spec licensee:
        commands:
        - /usr/bin/env sh .sqa/script.lovely-malachite-terrier.sh
        container: qc.lic_seedy-pumpkin-camel
  QC.Sec:
    repos:
      github.com/EOSC-synergy/sqaaas-api-spec gosec:
        commands:
        - /usr/bin/env sh .sqa/script.grumpy-cerulean-gorilla.sh
        container: qc.sec_skanky-sapphire-penguin
  QC.Ver:
    repos:
      github.com/EOSC-synergy/sqaaas-api-spec get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.stinky-lavender-wasp.sh
        container: qc.ver_gimpy-razzmatazz-cichlid
timeout: 1800
