config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-api-spec:
      branch: master
      repo: https://github.com/EOSC-synergy/sqaaas-api-spec
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: feature/gosec
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/EOSC-synergy/sqaaas-api-spec git:
        commands:
        - /usr/bin/env sh .sqa/script.randy-ivory-mandrill.sh
        container: qc.acc_boozy-cinnamon-catfish
  QC.Doc:
    repos:
      github.com/EOSC-synergy/sqaaas-api-spec find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.stealthy-olivine-starfish.sh
        container: qc.doc_woolly-cream-baboon
      github.com/EOSC-synergy/sqaaas-api-spec git:
        commands:
        - /usr/bin/env sh .sqa/script.randy-yellow-dogfish.sh
        container: qc.doc_ugly-cerise-antelope
      github.com/EOSC-synergy/sqaaas-api-spec markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.nippy-cardinal-retriever.sh
        container: qc.doc_gummy-sangria-slug
  QC.Lic:
    repos:
      github.com/EOSC-synergy/sqaaas-api-spec licensee:
        commands:
        - /usr/bin/env sh .sqa/script.muggy-red-quail.sh
        container: qc.lic_scanty-crimson-kakapo
  QC.Sec:
    repos:
      github.com/EOSC-synergy/sqaaas-api-spec gosec:
        commands:
        - /usr/bin/env sh .sqa/script.skinny-cyan-greyhound.sh
        container: qc.sec_nippy-pumpkin-hippopotamus
  QC.Ver:
    repos:
      github.com/EOSC-synergy/sqaaas-api-spec get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.skanky-harlequin-tarantula.sh
        container: qc.ver_stuffy-xanthic-bulldog
timeout: 1800
