config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-api-spec:
      branch: master
      repo: https://github.com/EOSC-synergy/sqaaas-api-spec
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: 1.6.0-alpha5
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/EOSC-synergy/sqaaas-api-spec git:
        commands:
        - /usr/bin/env sh .sqa/script.bumpy-bronze-dalmatian.sh
        container: qc.acc_smelly-amber-wrasse
  QC.Doc:
    repos:
      github.com/EOSC-synergy/sqaaas-api-spec find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.frumpy-plum-gar.sh
        container: qc.doc_squeaky-lime-whale
      github.com/EOSC-synergy/sqaaas-api-spec markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.boozy-cyan-russel.sh
        container: qc.doc_wheezy-emerald-cheetah
  QC.Lic:
    repos:
      github.com/EOSC-synergy/sqaaas-api-spec licensee:
        commands:
        - /usr/bin/env sh .sqa/script.wheezy-yellow-hound.sh
        container: qc.lic_grumpy-mustard-koala
  QC.Ver:
    repos:
      github.com/EOSC-synergy/sqaaas-api-spec is_semver.py:
        commands:
        - /usr/bin/env sh .sqa/script.squeaky-cardinal-forest.sh
        container: qc.ver_frumpy-champagne-salamander
timeout: 600
