config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-api-spec:
      branch: master
      repo: https://github.com/EOSC-synergy/sqaaas-api-spec
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: release/1.7.0
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/EOSC-synergy/sqaaas-api-spec git:
        commands:
        - /usr/bin/env sh .sqa/script.skanky-grey-elephant.sh
        container: qc.acc_shabby-orchid-panda
  QC.Doc:
    repos:
      github.com/EOSC-synergy/sqaaas-api-spec find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.sloppy-rose-crane.sh
        container: qc.doc_tasty-wheat-greyhound
      github.com/EOSC-synergy/sqaaas-api-spec git:
        commands:
        - /usr/bin/env sh .sqa/script.breezy-magenta-woodlouse.sh
        container: qc.doc_baggy-viridian-deer
      github.com/EOSC-synergy/sqaaas-api-spec markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.baggy-silver-numbat.sh
        container: qc.doc_thirsty-champagne-lemur
  QC.FAIR:
    repos:
      github.com/EOSC-synergy/sqaaas-api-spec F-UJI:
        commands:
        - /usr/bin/env sh .sqa/script.randy-cyan-hound.sh
        container: qc.fair_stealthy-grey-frise
  QC.Lic:
    repos:
      github.com/EOSC-synergy/sqaaas-api-spec licensee:
        commands:
        - /usr/bin/env sh .sqa/script.freaky-black-manatee.sh
        container: qc.lic_wimpy-khaki-antelope
  QC.Ver:
    repos:
      github.com/EOSC-synergy/sqaaas-api-spec get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.snazzy-malachite-reindeer.sh
        container: qc.ver_blurry-asparagus-magpie
timeout: 1800
