config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-api-spec:
      branch: master
      repo: https://github.com/EOSC-synergy/sqaaas-api-spec
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: release/1.7.0
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/EOSC-synergy/sqaaas-api-spec git:
        commands:
        - /usr/bin/env sh .sqa/script.stuffy-grey-earwig.sh
        container: qc.acc_wheezy-rust-eel
  QC.Doc:
    repos:
      github.com/EOSC-synergy/sqaaas-api-spec find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.squirrely-cornflower-wolfhound.sh
        container: qc.doc_gimpy-fuchsia-dane
      github.com/EOSC-synergy/sqaaas-api-spec git:
        commands:
        - /usr/bin/env sh .sqa/script.frumpy-brown-hare.sh
        container: qc.doc_dorky-zucchini-bird
      github.com/EOSC-synergy/sqaaas-api-spec markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.droopy-azure-dugong.sh
        container: qc.doc_gamy-ruby-kangaroo
  QC.FAIR:
    repos:
      github.com/EOSC-synergy/sqaaas-api-spec F-UJI:
        commands:
        - /usr/bin/env sh .sqa/script.hazy-platinum-eagle.sh
        container: qc.fair_muzzy-flax-serval
  QC.Lic:
    repos:
      github.com/EOSC-synergy/sqaaas-api-spec licensee:
        commands:
        - /usr/bin/env sh .sqa/script.dorky-chestnut-booby.sh
        container: qc.lic_randy-aqua-vulture
  QC.Ver:
    repos:
      github.com/EOSC-synergy/sqaaas-api-spec get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.skimpy-apricot-yak.sh
        container: qc.ver_nippy-puce-mongoose
timeout: 1800
