config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-api-spec:
      branch: master
      repo: https://github.com/EOSC-synergy/sqaaas-api-spec
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: release/1.7.0
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/EOSC-synergy/sqaaas-api-spec git:
        commands:
        - /usr/bin/env sh .sqa/script.dorky-lilac-liger.sh
        container: qc.acc_crappy-lime-warthog
  QC.Doc:
    repos:
      github.com/EOSC-synergy/sqaaas-api-spec find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.nerdy-bronze-budgerigar.sh
        container: qc.doc_flabby-ochre-bear
      github.com/EOSC-synergy/sqaaas-api-spec git:
        commands:
        - /usr/bin/env sh .sqa/script.skimpy-tangerine-dodo.sh
        container: qc.doc_cozy-tomato-walrus
      github.com/EOSC-synergy/sqaaas-api-spec markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.lousy-azure-caiman.sh
        container: qc.doc_jumpy-plum-turtle
  QC.Lic:
    repos:
      github.com/EOSC-synergy/sqaaas-api-spec licensee:
        commands:
        - /usr/bin/env sh .sqa/script.shaky-bistre-buzzard.sh
        container: qc.lic_foggy-charcoal-magpie
  QC.Ver:
    repos:
      github.com/EOSC-synergy/sqaaas-api-spec get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.wiggy-olive-rabbit.sh
        container: qc.ver_bluesy-olive-zonkey
timeout: 1800
