config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-api-spec:
      branch: master
      repo: https://github.com/EOSC-synergy/sqaaas-api-spec
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: 1.6.0-alpha5
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/EOSC-synergy/sqaaas-api-spec git:
        commands:
        - /usr/bin/env sh .sqa/script.scummy-viridian-hornet.sh
        container: qc.acc_gimpy-teal-lizard
  QC.Doc:
    repos:
      github.com/EOSC-synergy/sqaaas-api-spec find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.sickly-cobalt-vulture.sh
        container: qc.doc_craggy-tomato-loon
      github.com/EOSC-synergy/sqaaas-api-spec markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.stealthy-smalt-shrimp.sh
        container: qc.doc_sunny-sepia-cougar
  QC.Lic:
    repos:
      github.com/EOSC-synergy/sqaaas-api-spec licensee:
        commands:
        - /usr/bin/env sh .sqa/script.skimpy-emerald-drever.sh
        container: qc.lic_cranky-cornflower-ostrich
  QC.Ver:
    repos:
      github.com/EOSC-synergy/sqaaas-api-spec is_semver.py:
        commands:
        - /usr/bin/env sh .sqa/script.surly-olivine-crab.sh
        container: qc.ver_stealthy-scarlet-macaque
timeout: 600
