config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-api-spec:
      branch: master
      repo: https://github.com/EOSC-synergy/sqaaas-api-spec
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: release/1.7.0
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/EOSC-synergy/sqaaas-api-spec git:
        commands:
        - /usr/bin/env sh .sqa/script.droopy-denim-grasshopper.sh
        container: qc.acc_dorky-gold-avocet
  QC.Doc:
    repos:
      github.com/EOSC-synergy/sqaaas-api-spec find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.flimsy-red-albatross.sh
        container: qc.doc_ugly-heliotrope-dugong
      github.com/EOSC-synergy/sqaaas-api-spec git:
        commands:
        - /usr/bin/env sh .sqa/script.flimsy-sepia-iguana.sh
        container: qc.doc_smelly-brown-quokka
      github.com/EOSC-synergy/sqaaas-api-spec markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.beady-fuchsia-dragon.sh
        container: qc.doc_flimsy-jade-liger
  QC.FAIR:
    repos:
      github.com/EOSC-synergy/sqaaas-api-spec F-UJI:
        commands:
        - /usr/bin/env sh .sqa/script.queasy-magnolia-forest.sh
        container: qc.fair_goopy-chartreuse-markhor
  QC.Lic:
    repos:
      github.com/EOSC-synergy/sqaaas-api-spec licensee:
        commands:
        - /usr/bin/env sh .sqa/script.geeky-violet-sheep.sh
        container: qc.lic_greasy-chartreuse-albatross
  QC.Ver:
    repos:
      github.com/EOSC-synergy/sqaaas-api-spec get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.bumpy-maroon-abyssinian.sh
        container: qc.ver_gloppy-brass-binturong
timeout: 1800
