config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-api-spec:
      branch: master
      repo: https://github.com/EOSC-synergy/sqaaas-api-spec
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: 1.6.0-alpha5
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/EOSC-synergy/sqaaas-api-spec git:
        commands:
        - /usr/bin/env sh .sqa/script.sleepy-maroon-dragon.sh
        container: qc.acc_wheezy-eggplant-antelope
  QC.Doc:
    repos:
      github.com/EOSC-synergy/sqaaas-api-spec find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.wheezy-mustard-skunk.sh
        container: qc.doc_slimy-carmine-orangutan
      github.com/EOSC-synergy/sqaaas-api-spec markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.queasy-gold-bombay.sh
        container: qc.doc_silly-black-salamander
  QC.Lic:
    repos:
      github.com/EOSC-synergy/sqaaas-api-spec licensee:
        commands:
        - /usr/bin/env sh .sqa/script.lousy-copper-lynx.sh
        container: qc.lic_blurry-bistre-chow
  QC.Ver:
    repos:
      github.com/EOSC-synergy/sqaaas-api-spec is_semver.py:
        commands:
        - /usr/bin/env sh .sqa/script.woozy-puce-tarantula.sh
        container: qc.ver_dorky-olivine-dog
timeout: 600
