config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-api-spec:
      branch: master
      repo: https://github.com/EOSC-synergy/sqaaas-api-spec
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: 1.6.0-alpha5
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/EOSC-synergy/sqaaas-api-spec git:
        commands:
        - /usr/bin/env sh .sqa/script.freaky-cinnabar-badger.sh
        container: qc.acc_shabby-white-bullfrog
  QC.Doc:
    repos:
      github.com/EOSC-synergy/sqaaas-api-spec find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.flimsy-firebrick-hyrax.sh
        container: qc.doc_lovely-olive-booby
      github.com/EOSC-synergy/sqaaas-api-spec markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.muzzy-charcoal-crane.sh
        container: qc.doc_chummy-heliotrope-dhole
  QC.Lic:
    repos:
      github.com/EOSC-synergy/sqaaas-api-spec licensee:
        commands:
        - /usr/bin/env sh .sqa/script.sunny-burgundy-orangutan.sh
        container: qc.lic_tacky-corn-ant
  QC.Ver:
    repos:
      github.com/EOSC-synergy/sqaaas-api-spec is_semver.py:
        commands:
        - /usr/bin/env sh .sqa/script.sloppy-sangria-eel.sh
        container: qc.ver_snazzy-smalt-wasp
timeout: 600
