config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: 1.7.0-alpha2
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/eosc-synergy/sqaaas-api-spec:
      branch: master
      repo: https://github.com/eosc-synergy/sqaaas-api-spec
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/eosc-synergy/sqaaas-api-spec git:
        commands:
        - /usr/bin/env sh .sqa/script.cheeky-lemon-numbat.sh
        container: qc.acc_cranky-celadon-jellyfish
  QC.Doc:
    repos:
      github.com/eosc-synergy/sqaaas-api-spec find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.scummy-myrtle-audemer.sh
        container: qc.doc_zippy-orange-gar
      github.com/eosc-synergy/sqaaas-api-spec git:
        commands:
        - /usr/bin/env sh .sqa/script.shaky-alizarin-wolfhound.sh
        container: qc.doc_snippy-aqua-gar
      github.com/eosc-synergy/sqaaas-api-spec markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.pasty-lavender-beaver.sh
        container: qc.doc_blurry-aqua-caterpillar
  QC.FAIR:
    repos:
      github.com/eosc-synergy/sqaaas-api-spec F-UJI:
        commands:
        - /usr/bin/env sh .sqa/script.baggy-green-lynx.sh
        container: qc.fair_skanky-jade-lionfish
  QC.Lic:
    repos:
      github.com/eosc-synergy/sqaaas-api-spec licensee:
        commands:
        - /usr/bin/env sh .sqa/script.squirrely-vermilion-spitz.sh
        container: qc.lic_lousy-copper-dalmatian
  QC.Ver:
    repos:
      github.com/eosc-synergy/sqaaas-api-spec get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.tasty-green-discus.sh
        container: qc.ver_woozy-sepia-retriever
timeout: 1800
